[tool.poetry]
name = "todoist_api_python"
version = "0.1.7"
description = "Official Python SDK for the Todoist REST API."
readme = "README.md"
homepage = "https://github.com/Doist/todoist-api-python"
repository = "https://github.com/Doist/todoist-api-python"
documentation = "https://developer.todoist.com/rest/"
authors = ["Doist Developers <dev@doist.com>"]
keywords = ["todoist", "rest", "api", "python"]
license = "MIT"
classifiers = [
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.0.0"

[tool.poetry.dev-dependencies]
pytest = "^5.3.2"
black = "20.8b1"
flake8 = "^3.8.4"
pre-commit = "^2.9.0"
isort = "^5.6.4"
mypy = "^0.790"
responses = "^0.12.1"
pytest-asyncio = "^0.14.0"

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry>=1.0.5"]
build-backend = "poetry.masonry.api"
