[tool.poetry]
name = "todoist_api_python"
version = "0.1.0"
description = "A python wrapper for the Todoist REST API."
readme = "README.md"
homepage = "https://github.com/Doist/todoist-api-python"
repository = "https://github.com/Doist/todoist-api-python"
authors = ["Doist Developers <dev@doist.com>"]
license = "MIT"
classifiers = [
    "Intended Audience :: Developers",
    "Private :: Do Not Upload",
    ]
include = [
    "CHANGELOG.md"
]

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.25.1"

[tool.poetry.dev-dependencies]
pytest = "^5.3.2"
black = "20.8b1"
flake8 = "^3.8.4"
pre-commit = "^2.9.0"
isort = "^5.6.4"
mypy = "^0.790"

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry>=1.0.5"]
build-backend = "poetry.masonry.api"
